package sparktools;

/*
 * Planning : Eventually create Java GUI to handle these...
 * 
 * [folder]
 * <file>
 * 
 * <spark_tool Java jar>
 * [Grades]
 * 		[assignment_list] - contains list of files named after labs and used to write the workbook to copy & paste to online GB
 * 			<lab-name.txt> (generated by the file-write.bat file)
 * 		[batch_files] - contains batch files to be executed
 * 			<file-write.bat>
 * 			<lab-content-extractor.bat>
 * 			<lab-week-extractor.bat>
 * 		[gradebook_sheet] - destination for workbook listing all labs and student names
 * 			<workbook.xslx> (generated by the workbook service...reading names from assignment_list folder files)
 * 		[lab_weeks] - contains Week 1 - Week 4 folders...
 * 			[Week 1] (Should be based on the folders moved from zip_files)
 *			[Week 2] (Should be based on the folders moved from zip_files)
 *			[Week 3] (Should be based on the folders moved from zip_files)
 *			[Week 4] (Should be based on the folders moved from zip_files)
 * 		[zip_files] - contain the zip file(s) downloaded from rev pro
 * 			[spark-week-zip-file...] (Responsibility of the Trainer to place these zip files into this folder)
 * 
 * <<<NEXT UP>>> 
 * Initializer (first time creation) - possibly detect that no batch files exist?
 * 		[O] Validate environment
 * 		[O] Generate folders and Files in path file
 * 
 * BatchFile Creator:
 *  	Create files 
 *  		[O] zipfile extractor [pull Week folders out of extract Zips and place into 'lab_weeks'], 
 *  		[X] lab extractor [Unzip the contents within the lab_weeks (based on Bryn's file)] 
 *  		[O] file-writer [Write the name of students to text files (based on Bryn's file)]
 *  	[O] Create folders  		
 *  
 * BatchFile Executor:
 * 		[O] Execute file-writer batch file
 * 
 * Application Execution:
 * 		[X] Create GUI
 * 		[X] Option to ask if they want to generate new Lab .txts first or just create the Excel
 */
public class Outline { }
